### ISSUE TITLE
[JOSS review] Cannot determine CRS in Maxent vignette

### ISSUE THREAD

**Issue by gabrieldansereau** [earth-chris/elapid#90]
Hi @earth-chris! I'm running into a CRS error when trying to reproduce the Maxent example (the geospatial data one runs fine and thank you for making it as detailed, by the way!)

Everything runs fine until this line in the second cell:
```python-repl
>>> merged = ela.stack_geodataframes(presence, background, add_class_label=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gabriel/github/elapid/elapid/geo.py", line 101, in stack_geodataframes
    merged = pd.concat((presence[matching], background[matching]), axis=0, ignore_index=True)
  File "/home/gabriel/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/gabriel/.local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 381, in concat
    return op.get_result()
  File "/home/gabriel/.local/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 616, in get_result
    new_data = concatenate_managers(
  File "/home/gabriel/.local/lib/python3.10/site-packages/pandas/core/internals/concat.py", line 226, in concatenate_managers
    values = concat_compat(vals, axis=1)
  File "/home/gabriel/.local/lib/python3.10/site-packages/pandas/core/dtypes/concat.py", line 133, in concat_compat
    return cls._concat_same_type(to_concat)
  File "/home/gabriel/.local/lib/python3.10/site-packages/geopandas/array.py", line 1323, in _concat_same_type
    return GeometryArray(data, crs=_get_common_crs(to_concat))
  File "/home/gabriel/.local/lib/python3.10/site-packages/geopandas/array.py", line 1413, in _get_common_crs
    raise ValueError(
ValueError: Cannot determine common CRS for concatenation inputs, got ['WGS 84 / UTM zone 10N', 'WGS 84 / UTM zone 10N']. Use `to_crs()` to transform geometries to the same CRS before merging.
```

Probably just an easy thing to update I hope

**Comment by earth-chris** [comment]
☹️ this is annoying. the two crs _do_ match. i think it's a recent geopandas version thing. i think i can fix this rq. please hold

**Comment by earth-chris** [comment]
in the meantime @gabrieldansereau, if you add the following line to the code block it should work:

```python
# merge datasets and read the covariates at each point location
backround.crs = presence.crs
merged = ela.stack_geodataframes(presence, background, add_class_label=True)
annotated = ela.annotate(merged, rasters, drop_na=True, quiet=True)

# etc.
```

**Comment by gabrieldansereau** [comment]
That works, thanks! (fixing the small typo in `background.crs`)

It's fine for me if you add that to the example. I'm just making sure everything is reproducible for the JOSS review.
